name: CI

on:
  push:
    branches: master
    tags: [ '**' ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dump Context
        run: echo '${{ toJSON( github ) }}'
      - name: Dump ENV
        run: set
      - name: Checkout Wiki
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}.wiki
      - run: |
          touch actions.log
          echo '${{ github.event.head_commit.id }} ${{ github.event.head_commit.message }}' >> actions.log
          git add .
          git commit -m 'Recording action run #${{ github.run_id }}'
          git push origin master
        env:
          GIT_AUTHOR_EMAIL: ${{ github.actor }}@users.noreply.github.com
          GIT_AUTHOR_NAME: ${{ github.actor }}
          GIT_COMMITTER_EMAIL: ${{ github.actor }}@users.noreply.github.com
          GIT_COMMITTER_NAME: ${{ github.actor }}
