name: CI

on:
  push:
    branches: master
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dump Context
        run: echo '${{ toJSON( github ) }}'
      - name: Checkout Wiki
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}.wiki
      - run: ls -alh
