name: CI

.job_template: &job_definition  # Hidden key that defines an anchor named 'job_definition'
  run: echo '${{ toJSON( job ) }}'

on:
  push:
    branches: master
    tags: [ '**' ]
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dump Context
        run: echo '${{ toJSON( github ) }}'
      - name: Dump ENV
        run: set
      - test1:
        <<: *job_definition           # Merge the contents of the 'job_definition' alias
        name: Test Job 1
        env:
          foo: bar
      - test2:
        <<: *job_definition           # Merge the contents of the 'job_definition' alias
        name: Test Job 2
        env:
          foo: baz
      - name: Checkout Wiki
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}.wiki
      - run: |
          touch actions.log
          echo '${{ github.event.head_commit.id }} ${{ github.event.head_commit.message }}' >> actions.log
          git add .
          git commit -m 'Recording action run #${{ github.run_id }}'
          git push origin master
        env:
          GIT_AUTHOR_EMAIL: ${{ github.actor }}@users.noreply.github.com
          GIT_AUTHOR_NAME: ${{ github.actor }}
          GIT_COMMITTER_EMAIL: ${{ github.actor }}@users.noreply.github.com
          GIT_COMMITTER_NAME: ${{ github.actor }}
